sudo: false
language: c

# Build matrix
compiler:
  - gcc
  - clang

env:
  - BUILD_SHARED_LIBS="OFF" CGREEN_WITH_CXX="OFF"
  - BUILD_SHARED_LIBS="ON" CGREEN_WITH_CXX="OFF"
  - BUILD_SHARED_LIBS="OFF" CGREEN_WITH_CXX="ON"
  - BUILD_SHARED_LIBS="ON" CGREEN_WITH_CXX="ON"

addons:
  apt:
    packages:
    - cmake
    - lcov
    - g++

before_install:
  - if [[ $CC == gcc ]] ; then export CXX=g++ ; else export CXX=clang++ ; fi
  - $CC --version
  - $CXX --version
  - gem install coveralls-lcov
  - if [ "$CC" = "gcc" ]; then export WITH_GCOV=ON; else WITH_GCOV=OFF; fi

script:
  - mkdir -p build
  - cd build
  - cmake -DCGREEN_WITH_CXX:BOOL=$CGREEN_WITH_CXX -DCGREEN_WITH_UNIT_TESTS:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=$BUILD_SHARED_LIBS -DCGREEN_INTERNAL_WITH_GCOV:BOOL=$WITH_GCOV ..
  - make -j2
  - ctest --output-on-failure

after_success:
  - if [ "$CC" = "gcc" ];
    then
      lcov -d tests -d src -base-directory .. -c -o coverage.info;
      lcov --remove coverage.info '/usr/*' -o coverage.info;
      cd ..;
      coveralls-lcov build/coverage.info;
    fi

notifications:
  slack: cgreen:EC3bZqwnyBsaqyeIndEewwNT
